// レバメモ本文の整形: 旧「タイムライン（時刻）」表記を撤廃し、順序を示す連番に置き換える。
//
// 背景: 動画編集のカットで各ポイントの時刻が実動画とズレ、意味をなさなくなった。
//       時刻そのものをデータから取り除き、並び順（連番）で示す方針に統一する。
//
// この共通処理を 2 箇所で使う:
//   1. fetch-memos.mjs … Google Docs からの再生成時にも時刻が残らないようにする
//   2. このファイルを直接実行 … 既存 memoContents.generated.ts を再フェッチせず整形する
//      （非公開化した Doc があっても本文を失わないよう、ネットワークに依存しない）
//
// ■ なぜ連番を生成データ側で振るのか
//   元データの構造は一様ではない（時刻が見出しと同一行 / 時刻だけ単独行 + 見出しは次行 /
//   全行が箇条書き接頭辞付き など）。時刻を消すと、表示時には「ポイント見出し行」と
//   「補足の継続行（→ … など）」を確実に区別できなくなる。時刻こそが各ポイントの開始位置を
//   示す唯一の確実なアンカーだったため、時刻が見えているこの整形段階で並び順から連番を確定し、
//   "NN<空白>見出し" という単一の形に正規化する。番号は手書きではなく並び順から自動採番。
//   表示側はこの "NN " を読み取って丸バッジ＋見出しを描画する。

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// 行頭（任意の箇条書き接頭辞を許容）の時刻。範囲末尾は時刻 or「終わり」、区切りは全/半角｜やスペース。
// 例: "00:05〜00:39 見出し" / "00:00〜00:40｜見出し" / "* * 00:00〜01:12 見出し" / "03:32〜終わり 見出し"
//     "00:00〜00:40"（時刻だけで見出しは次行）も捕捉する（その場合 group1 は空）。
const POINT_LINE = /^(?:[\s　*・●＊•-]+)?\d{1,2}:\d{2}(?:\s*[〜~]\s*(?:\d{1,2}:\d{2}|終わり))?\s*[｜|]?\s*(.*)$/;

// 時刻ではなく ◾️/■ 等の記号で「動画のながれ」のポイントを区切る記法（例: video #15）。
// 記号見出しも並び順から連番化する。先頭の空白・装飾記号は許容。
const SQUARE_HEADING = /^(?:[\s　*-]+)?[◾◼■▪▫◻]️?\s*(.+)$/;

const FLOW_HEADER = 'タイムライン別の重要ポイント';
const FLOW_HEADER_NEW = '動画のながれ';

// テンプレ雛形の括弧注記（文字数・個数・版表記）を1行から除去する。全動画に適用。
// 例: 「全体要約（200〜400文字）」→「全体要約」、「まとめポイント3つ（強化版）」→「まとめポイント3つ」
function stripTemplateArtifacts(line) {
  return line
    .replace(/[（(]\s*\d+\s*[〜～~]\s*\d+\s*文字\s*[）)]/g, '')
    .replace(/[（(]\s*\d+\s*[〜～~]\s*\d+\s*個\s*[）)]/g, '')
    .replace(/[（(]\s*(?:修正版|強化版|整理版)\s*[）)]/g, '')
    .replace(/[ 　]+$/, '');
}

export function cleanMemoText(text) {
  let lines = text.split('\n');

  // A-1: ソースDocが全体箇条書きリスト由来で各行に `* ` `* * ` が混入した破損ケース（例: #18 / video-1188100570）。
  // 「二重スター(`* *`)で始まる行が1つでも存在する」ことを破損シグネチャとし、その動画にだけ行頭スター接頭辞を除去する。
  // 通常 `* ` を箇条書きマーカーとして使う動画（#2/#11/#14/#45 等）には二重スターが無いため一切触れない。
  const starCorrupted = lines.some((l) => /^\s*\*\s+\*\s/.test(l));
  if (starCorrupted) {
    lines = lines
      .map((l) => l.replace(/^\s*(?:\*\s+)+/, ''))               // 行頭の `* ` 繰り返しを除去（`* * ・` → `・`）
      .filter((l, idx) => !(idx === 0 && /レバメモ$/.test(l.trim()))) // 先頭のDocタイトルJunk行（"６−345 レバメモ" 等）を除去
      .map((l) => (l.trim() === '*' ? '' : l));                  // 単独 `*` 残骸 → 空行化
  }

  // A-2: テンプレ雛形の括弧注記を全行から除去。
  lines = lines.map(stripTemplateArtifacts);

  // A-3: `**bold**` 記法は廃止（コース全体で1箇所のみ＝正本フォーマットではない）。装飾を外して素のテキストにする。
  lines = lines.map((l) => l.replace(/\*\*([^*\n]+)\*\*/g, '$1'));

  const out = [];
  let inFlow = false;
  let counter = 0;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // セクション見出し「タイムライン別の重要ポイント」→「動画のながれ」（【】・接尾辞・箇条書き付きも許容）。
    // 旧表記だけでなく、既に「動画のながれ」へ移行済みの動画（例: video #15）でもフロー区間に入る。
    if (trimmed.includes(FLOW_HEADER) || trimmed.includes(FLOW_HEADER_NEW)) {
      out.push(line.replace(FLOW_HEADER, FLOW_HEADER_NEW));
      inFlow = true;
      counter = 0;
      continue;
    }

    // 「動画のながれ」セクションの終端（次セクションに入ったら連番付与を止める）
    if (inFlow && (trimmed.includes('行動リスト') || trimmed.includes('まとめポイント'))) {
      inFlow = false;
      out.push(line);
      continue;
    }

    // 「動画のながれ」セクション内のポイント行を連番見出しへ正規化
    if (inFlow) {
      const m = trimmed.match(POINT_LINE);
      if (m) {
        counter += 1;
        let heading = m[1].trim();
        // 時刻だけが単独行のケース（format C）は、続く最初の非空行を見出しとして取り込む
        if (!heading) {
          let j = i + 1;
          while (j < lines.length && !lines[j].trim()) j++;
          if (j < lines.length) {
            heading = lines[j].trim();
            i = j; // 見出し行まで消費
          }
        }
        out.push(`${String(counter).padStart(2, '0')} ${heading}`.trimEnd());
        continue;
      }
      // 記号見出し（◾️/■ 等）も並び順から連番見出しへ正規化する。
      // 既に "NN 見出し" 済みの行は POINT_LINE にも SQUARE_HEADING にもマッチせず素通りする（冪等）。
      const sq = trimmed.match(SQUARE_HEADING);
      if (sq) {
        counter += 1;
        out.push(`${String(counter).padStart(2, '0')} ${sq[1].trim()}`.trimEnd());
        continue;
      }
    }

    out.push(line);
  }

  return out
    .join('\n')
    .replace(
      /腕元で鍵盤を下げられる位置に体を置くこと。/g,
      '腕ごと鍵盤を下げられる位置に体を置くこと。',
    );
}

// 直接実行されたとき: 既存の生成物をその場で整形して書き戻す。
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const __dirname = dirname(fileURLToPath(import.meta.url));
  const file = join(__dirname, '..', 'src', 'lib', 'memoContents.generated.ts');
  const src = await readFile(file, 'utf8');
  const start = src.indexOf('{');
  const end = src.lastIndexOf('}');
  const obj = JSON.parse(src.slice(start, end + 1));
  const cleaned = {};
  for (const [k, v] of Object.entries(obj)) cleaned[k] = cleanMemoText(v);
  const header =
    '// AUTO-GENERATED by scripts/fetch-memos.mjs — DO NOT EDIT.\n' +
    '// 再生成: node scripts/fetch-memos.mjs\n\n' +
    'export const memoContents: Record<string, string> = ';
  await writeFile(file, header + JSON.stringify(cleaned, null, 2) + ';\n', 'utf8');
  console.log(`cleaned ${Object.keys(cleaned).length} memos → ${file}`);
}
