// レバメモ（Google Docs）一括フェッチ & memoContents.generated.ts 生成スクリプト
//
// 使い方: node scripts/fetch-memos.mjs
//
// - scripts/memo_urls.txt から `vimeoId | DocURL` を読み込む
// - 各 Doc を export?format=txt で取得（公開「リンクを知っている全員」前提・認証不要）
// - 非公開/削除は content-type と status で検知してスキップ
// - 取得テキストを正規化（BOM除去・CRLF→LF・連続空行圧縮・行末trim）
// - 生テキストを scripts/memos_raw/{vimeoId}.txt に保存（目視点検用）
// - src/lib/memoContents.generated.ts を生成（Record<videoId, string>）
// - src/lib/lmsData.ts の各動画 memoUrl を実URLに更新

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { cleanMemoText } from './clean-memo.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const URLS_FILE = join(__dirname, 'memo_urls.txt');
const RAW_DIR = join(__dirname, 'memos_raw');
const GENERATED_FILE = join(ROOT, 'src', 'lib', 'memoContents.generated.ts');
const LMS_DATA_FILE = join(ROOT, 'src', 'lib', 'lmsData.ts');

const DELAY_MS = 300;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function extractDocId(url) {
  const m = url.match(/\/document\/d\/([A-Za-z0-9_-]+)/);
  return m ? m[1] : null;
}

function normalize(text) {
  let t = text;
  // BOM除去
  if (t.charCodeAt(0) === 0xfeff) t = t.slice(1);
  // 改行統一
  t = t.replace(/\r\n?/g, '\n');
  // 行末の空白を除去
  t = t.split('\n').map((line) => line.replace(/[ \t　]+$/, '')).join('\n');
  // 3連以上の空行を2連（空行1つ）に圧縮
  t = t.replace(/\n{3,}/g, '\n\n');
  // 全体の前後空白を除去
  t = t.trim();
  return t;
}

async function fetchDocText(docId) {
  const url = `https://docs.google.com/document/d/${docId}/export?format=txt`;
  const res = await fetch(url, { redirect: 'follow' });
  const ct = res.headers.get('content-type') || '';
  if (!res.ok) {
    throw new Error(`HTTP ${res.status}`);
  }
  if (!ct.includes('text/plain')) {
    // 非公開ドキュメントはログインHTML(text/html)が返る
    throw new Error(`non-public (content-type: ${ct})`);
  }
  return await res.text();
}

async function fetchWithRetry(docId) {
  try {
    return await fetchDocText(docId);
  } catch (e) {
    await sleep(DELAY_MS * 2);
    return await fetchDocText(docId); // 1回リトライ（失敗時は例外送出）
  }
}

async function main() {
  await mkdir(RAW_DIR, { recursive: true });

  const raw = await readFile(URLS_FILE, 'utf8');
  const entries = raw
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean)
    .map((line) => {
      const [vimeoId, url] = line.split('|').map((s) => s.trim());
      return { vimeoId, url, videoId: `video-${vimeoId}`, docId: extractDocId(url) };
    });

  console.log(`対象 ${entries.length} 件をフェッチします...\n`);

  const memoContents = {};
  const report = { ok: [], empty: [], failed: [] };

  for (const e of entries) {
    process.stdout.write(`[${e.vimeoId}] `);
    if (!e.docId) {
      console.log('✗ Doc ID 抽出失敗');
      report.failed.push({ ...e, reason: 'no doc id' });
      memoContents[e.videoId] = '';
      continue;
    }
    try {
      const text = await fetchWithRetry(e.docId);
      const normalized = normalize(text);
      // 生テキストは点検用に原本のまま保存し、生成データ側だけ時刻を撤廃する。
      await writeFile(join(RAW_DIR, `${e.vimeoId}.txt`), text, 'utf8');
      const cleaned = cleanMemoText(normalized);
      memoContents[e.videoId] = cleaned;
      if (cleaned.length === 0) {
        console.log('△ 空（中身なし）');
        report.empty.push(e);
      } else {
        console.log(`✓ ${cleaned.length} 文字`);
        report.ok.push(e);
      }
    } catch (err) {
      console.log(`✗ ${err.message}`);
      report.failed.push({ ...e, reason: err.message });
      memoContents[e.videoId] = '';
    }
    await sleep(DELAY_MS);
  }

  // 生成ファイル出力
  const header =
    '// AUTO-GENERATED by scripts/fetch-memos.mjs — DO NOT EDIT.\n' +
    '// 再生成: node scripts/fetch-memos.mjs\n\n' +
    'export const memoContents: Record<string, string> = ';
  await writeFile(GENERATED_FILE, header + JSON.stringify(memoContents, null, 2) + ';\n', 'utf8');

  // lmsData.ts の memoUrl を更新
  let lms = await readFile(LMS_DATA_FILE, 'utf8');
  let urlPatched = 0;
  for (const e of entries) {
    const re = new RegExp(
      `("id": "${e.videoId}",[\\s\\S]*?"memoUrl": )"[^"]*"`,
    );
    const before = lms;
    lms = lms.replace(re, `$1${JSON.stringify(e.url)}`);
    if (lms !== before) urlPatched++;
  }
  await writeFile(LMS_DATA_FILE, lms, 'utf8');

  console.log('\n========== 結果 ==========');
  console.log(`成功(本文あり): ${report.ok.length}`);
  console.log(`空ドキュメント : ${report.empty.length}${report.empty.length ? ' → ' + report.empty.map((e) => e.vimeoId).join(', ') : ''}`);
  console.log(`失敗           : ${report.failed.length}${report.failed.length ? ' → ' + report.failed.map((e) => e.vimeoId + '(' + e.reason + ')').join(', ') : ''}`);
  console.log(`memoUrl 更新   : ${urlPatched}/${entries.length}`);
  console.log(`生成ファイル   : ${GENERATED_FILE}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
