-- 公開ログインAPIの連続送信を、複数のVercelインスタンス間でも制限する。
-- メールアドレスやIPアドレスの生値、Magic Link本体は保存しない。
create table if not exists public.auth_login_requests (
  id bigint generated by default as identity primary key,
  email_hash text not null,
  request_fingerprint text not null,
  outcome text not null check (
    outcome in ('accepted', 'sent', 'skipped_unknown', 'failed', 'rate_limited')
  ),
  created_at timestamptz not null default now()
);

create index if not exists auth_login_requests_email_created_idx
  on public.auth_login_requests (email_hash, created_at desc);

create index if not exists auth_login_requests_fingerprint_created_idx
  on public.auth_login_requests (request_fingerprint, created_at desc);

alter table public.auth_login_requests enable row level security;
-- Service Roleを使うサーバーAPI以外からは読み書きさせない。

-- 判定と記録を同一トランザクションで行い、同時リクエストによる制限回避を防ぐ。
create or replace function public.claim_auth_login_request(
  p_email_hash text,
  p_request_fingerprint text,
  p_email_cooldown_seconds integer default 60,
  p_fingerprint_window_seconds integer default 600,
  p_fingerprint_max_requests integer default 10
)
returns table(request_id bigint, allowed boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_allowed boolean;
  v_request_id bigint;
begin
  if length(p_email_hash) <> 64 or length(p_request_fingerprint) <> 64 then
    raise exception 'invalid login request fingerprint';
  end if;

  perform pg_advisory_xact_lock(hashtextextended('email:' || p_email_hash, 0));
  perform pg_advisory_xact_lock(hashtextextended('fingerprint:' || p_request_fingerprint, 0));

  v_allowed := not exists (
    select 1
    from public.auth_login_requests
    where email_hash = p_email_hash
      and outcome <> 'rate_limited'
      and created_at >= now() - make_interval(secs => p_email_cooldown_seconds)
  ) and (
    select count(*)
    from public.auth_login_requests
    where request_fingerprint = p_request_fingerprint
      and outcome <> 'rate_limited'
      and created_at >= now() - make_interval(secs => p_fingerprint_window_seconds)
  ) < p_fingerprint_max_requests;

  insert into public.auth_login_requests (email_hash, request_fingerprint, outcome)
  values (
    p_email_hash,
    p_request_fingerprint,
    case when v_allowed then 'accepted' else 'rate_limited' end
  )
  returning id into v_request_id;

  return query select v_request_id, v_allowed;
end;
$$;

revoke all on function public.claim_auth_login_request(text, text, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.claim_auth_login_request(text, text, integer, integer, integer)
  to service_role;
