-- ログイン問い合わせを事務担当者だけで一次切り分けできるようにする。
-- 管理者権限とは分離し、サポート画面の閲覧・再送だけを個別に許可する。

create table if not exists public.support_agents (
  user_id uuid primary key references public.users(id) on delete cascade,
  enabled boolean not null default true,
  can_view_auth_status boolean not null default true,
  can_resend_login_email boolean not null default true,
  can_repair_profile boolean not null default false,
  created_by uuid references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.support_agents enable row level security;

drop policy if exists "Support agents can view own permissions" on public.support_agents;
create policy "Support agents can view own permissions"
  on public.support_agents
  for select
  using (auth.uid() = user_id);

-- 付与・変更は service role を使う管理APIだけに限定する。
-- INSERT / UPDATE / DELETE のRLSポリシーは意図的に作らない。

create table if not exists public.auth_email_events (
  id bigint generated by default as identity primary key,
  provider_event_id text not null unique,
  provider_email_id text,
  recipient_email text not null,
  event_type text not null,
  email_kind text not null default 'other',
  occurred_at timestamptz not null,
  failure_reason text,
  created_at timestamptz not null default now()
);

create index if not exists auth_email_events_recipient_occurred_idx
  on public.auth_email_events (recipient_email, occurred_at desc);

alter table public.auth_email_events enable row level security;
-- 配信履歴には個人情報を含むため、ブラウザからの直接アクセスは許可しない。

create table if not exists public.support_action_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.users(id) on delete set null,
  target_user_id uuid references public.users(id) on delete set null,
  target_email text not null,
  action text not null,
  result text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists support_action_logs_target_created_idx
  on public.support_action_logs (target_email, created_at desc);

alter table public.support_action_logs enable row level security;
-- 監査ログは改変防止のため、service role 経由でのみ読み書きする。

create table if not exists public.auth_callback_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete set null,
  outcome text not null check (outcome in ('success', 'failure')),
  error_code text,
  request_host text,
  created_at timestamptz not null default now()
);

create index if not exists auth_callback_events_user_created_idx
  on public.auth_callback_events (user_id, created_at desc);

alter table public.auth_callback_events enable row level security;
-- 認証コードやMagic Link本体は保存しない。
